# Search package from file: 
# tlmgr search --global --file <FILENAME.sty>

sudo tlmgr install amscls
sudo tlmgr install amsfonts
sudo tlmgr install amsmath
sudo tlmgr install xint 
sudo tlmgr install preprint
sudo tlmgr install booktabs
sudo tlmgr install caption
sudo tlmgr install comment
sudo tlmgr install cm-super
sudo tlmgr install cmap
sudo tlmgr install doclicense
sudo tlmgr install draftwatermark
sudo tlmgr install environ
sudo tlmgr install etoolbox
sudo tlmgr install fancyhdr
sudo tlmgr install float
sudo tlmgr install fontaxes
sudo tlmgr install geometry
sudo tlmgr install graphics
sudo tlmgr install hyperref
sudo tlmgr install hyperxmp
sudo tlmgr install iftex
sudo tlmgr install inconsolata
sudo tlmgr install libertine
sudo tlmgr install ncctools
sudo tlmgr install microtype
sudo tlmgr install mmap
sudo tlmgr install count1to
sudo tlmgr install multitoc
sudo tlmgr install prelim2e
sudo tlmgr install ragged2e
sudo tlmgr install everyshi
sudo tlmgr install everysel
sudo tlmgr install mweights
sudo tlmgr install natbib
sudo tlmgr install newtx
sudo tlmgr install oberdiek
sudo tlmgr install pdftex
sudo tlmgr install refcount
sudo tlmgr install setspace
sudo tlmgr install textcase
sudo tlmgr install totpages
sudo tlmgr install trimspaces
sudo tlmgr install upquote
sudo tlmgr install url
sudo tlmgr install xcolor
sudo tlmgr install xkeyval
sudo tlmgr install xstring
